version: "3.4"

services:
  identityserverwithaspnetidentity:
    image: ${DOCKER_REGISTRY}identityserverwithaspnetidentity
    build:
      context: .
      dockerfile: IdentityServerWithAspNetIdentity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
